name: Cypress

on: [push]

jobs:
  cypress:
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          browser: chrome
          headless: true
          wait-on: 'http://localhost:3000'
          spec: cypress/integration/start_screen_spec.ts,cypress/integration/input_data_spec.ts
